import { useEffect, useState } from 'react'
import {
  PageBanner,
  Button,
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  SectionHeader,
  Badge,
  Icon,
  EmptyState,
} from '../components'
import { useJobs } from '../stores/useJobs'
import { getCriteria, confirmCriteria } from '../lib/endpoints'
import type { Criterion, Importance } from '../lib/schemas'

const IMPORTANCE: { value: Importance; label: string }[] = [
  { value: 'must_have', label: 'Must have' },
  { value: 'very_important', label: 'Very important' },
  { value: 'important', label: 'Important' },
  { value: 'good_to_have', label: 'Good to have' },
]

export default function JobPosts() {
  const loadJobs = useJobs((s) => s.load)
  const jobs = useJobs((s) => s.jobs)
  const loaded = useJobs((s) => s.loaded)
  const error = useJobs((s) => s.error)
  const [selected, setSelected] = useState('')
  const [criteria, setCriteria] = useState<Criterion[]>([])
  const [status, setStatus] = useState<'draft' | 'confirmed'>('draft')

  useEffect(() => {
    loadJobs()
  }, [loadJobs])

  // Default the selection to the first real job once jobs arrive.
  useEffect(() => {
    if (jobs.length && !jobs.some((j) => j.jd_id === selected)) {
      setSelected(jobs[0].jd_id)
    }
  }, [jobs, selected])

  useEffect(() => {
    if (!selected) {
      setCriteria([])
      return
    }
    let alive = true
    getCriteria(selected)
      .then((c) => {
        if (alive) {
          setCriteria(c.criteria)
          setStatus(c.status)
        }
      })
      .catch(() => {
        if (alive) {
          setCriteria([])
          setStatus('draft')
        }
      })
    return () => {
      alive = false
    }
  }, [selected])

  const setCriterion = (i: number, text: string) =>
    setCriteria((cs) => cs.map((c, j) => (j === i ? { ...c, criterion: text } : c)))
  const setImportance = (i: number, imp: Importance) =>
    setCriteria((cs) => cs.map((c, j) => (j === i ? { ...c, importance: imp } : c)))
  const removeCriterion = (i: number) => setCriteria((cs) => cs.filter((_, j) => j !== i))
  const addCriterion = () =>
    setCriteria((cs) => [...cs, { criterion: '', importance: 'important' }])
  const confirm = () => {
    setStatus('confirmed')
    confirmCriteria(selected).catch(() => {
      /* re-fetched on next selection; UI already reflects intent */
    })
  }

  if (error) {
    return (
      <div className="page">
        <PageBanner title="Job posts" />
        <Card><EmptyState icon="alert" title="Couldn't load job posts" hint={error} /></Card>
      </div>
    )
  }
  if (loaded && jobs.length === 0) {
    return (
      <div className="page">
        <PageBanner title="Job posts" actions={<Button icon="plus">New job post</Button>} />
        <Card><EmptyState icon="briefcase" title="No job posts yet" hint="Job descriptions created in the pipeline appear here for criteria review." /></Card>
      </div>
    )
  }

  const selectedJob = jobs.find((j) => j.jd_id === selected)

  return (
    <div className="page">
      <PageBanner
        title="Job posts"
        subtitle={`${jobs.length} post${jobs.length === 1 ? '' : 's'}`}
        actions={<Button icon="plus">New job post</Button>}
      />
      <div className="jp-grid">
        <div className="jp-jobs">
          {jobs.map((j) => (
            <button
              key={j.jd_id}
              className={`jp-job ${j.jd_id === selected ? 'on' : ''}`}
              onClick={() => setSelected(j.jd_id)}
            >
              <div className="t">
                {j.title}
                <Badge variant={j.status === 'Active' ? 'strong' : 'neutral'}>{j.status ?? 'Draft'}</Badge>
              </div>
              <div className="m">
                {j.applicants != null && <span><b>{j.applicants}</b> applicants</span>}
                {j.shortlisted != null ? <span><b>{j.shortlisted}</b> shortlisted</span> : <span>criteria review</span>}
              </div>
            </button>
          ))}
        </div>

        <Card>
          <CardHeader>
            <SectionHeader title="Match criteria" subtitle={`${selectedJob?.title ?? ''} · generated by AI from the JD`} />
            <span className={`ce-status ${status}`} style={{ marginLeft: 'auto' }}>
              <Icon name={status === 'confirmed' ? 'check' : 'alert'} />
              {status === 'confirmed' ? 'Confirmed' : 'Draft — review to lock'}
            </span>
          </CardHeader>
          <CardBody>
            {criteria.length === 0 && (
              <p style={{ color: 'var(--text-muted)', fontSize: 13, margin: '4px 0 12px' }}>
                No criteria yet for this job — add them manually below.
              </p>
            )}
            {criteria.map((c, i) => (
              <div className="crit-row" key={i}>
                <span className="grip"><Icon name="grip" /></span>
                <input
                  className="crit-input"
                  value={c.criterion}
                  placeholder="Describe the criterion…"
                  onChange={(e) => setCriterion(i, e.target.value)}
                  aria-label={`Criterion ${i + 1}`}
                />
                <select
                  className={`imp-select ${c.importance === 'must_have' ? 'must' : ''}`}
                  value={c.importance}
                  onChange={(e) => setImportance(i, e.target.value as Importance)}
                  aria-label={`Importance for criterion ${i + 1}`}
                >
                  {IMPORTANCE.map((o) => (
                    <option key={o.value} value={o.value}>
                      {o.label}
                    </option>
                  ))}
                </select>
                <button className="crit-rm" onClick={() => removeCriterion(i)} aria-label="Remove criterion">
                  <Icon name="x" />
                </button>
              </div>
            ))}
            <button className="crit-add" onClick={addCriterion}>
              <Icon name="plus" />Add criterion
            </button>
          </CardBody>
          <CardFooter>
            <Button icon="check" onClick={confirm} disabled={status === 'confirmed'}>
              {status === 'confirmed' ? 'Confirmed' : 'Confirm criteria'}
            </Button>
            <Button variant="ghost" onClick={() => setStatus('draft')}>Regenerate</Button>
            <span className="ce-note">Scoring locks to these weights once confirmed. Candidates aren't scored until then.</span>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}
