import { useEffect, useState } from 'react'
import {
  PageBanner,
  Button,
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  SectionHeader,
  Badge,
  Icon,
} from '../components'
import { useJobs } from '../stores/useJobs'
import { getCriteria, confirmCriteria } from '../lib/endpoints'
import type { JobPost, Criterion, Importance } from '../lib/schemas'

const IMPORTANCE: { value: Importance; label: string }[] = [
  { value: 'must_have', label: 'Must have' },
  { value: 'very_important', label: 'Very important' },
  { value: 'important', label: 'Important' },
  { value: 'good_to_have', label: 'Good to have' },
]

const DEMO_JOBS: JobPost[] = [
  { jd_id: 'sbe', title: 'Senior Backend Engineer', status: 'Active', applicants: 41, shortlisted: 9 },
  { jd_id: 'pd', title: 'Product Designer', status: 'Draft', applicants: 0 },
  { jd_id: 'do', title: 'DevOps Engineer', status: 'Draft', applicants: 0 },
]

const DEMO_CRITERIA: Criterion[] = [
  { criterion: '5+ yrs building distributed / event-driven backends', importance: 'must_have' },
  { criterion: 'Strong Python + FastAPI, production REST APIs', importance: 'must_have' },
  { criterion: 'Database performance tuning (Postgres)', importance: 'very_important' },
  { criterion: 'Cloud infrastructure (AWS), containers', importance: 'important' },
  { criterion: 'Fintech / regulated-domain experience', importance: 'good_to_have' },
]

export default function JobPosts() {
  const loadJobs = useJobs((s) => s.load)
  const storeJobs = useJobs((s) => s.jobs)
  const [criteria, setCriteria] = useState<Criterion[]>(DEMO_CRITERIA)
  const [status, setStatus] = useState<'draft' | 'confirmed'>('draft')

  useEffect(() => {
    loadJobs()
  }, [loadJobs])

  const jobs = storeJobs.length ? storeJobs : DEMO_JOBS
  const [selected, setSelected] = useState(jobs[0]?.jd_id ?? 'sbe')

  useEffect(() => {
    let alive = true
    getCriteria(selected)
      .then((c) => {
        if (alive) {
          setCriteria(c.criteria)
          setStatus(c.status)
        }
      })
      .catch(() => {
        if (alive) {
          setCriteria(DEMO_CRITERIA)
          setStatus('draft')
        }
      })
    return () => {
      alive = false
    }
  }, [selected])

  const setCriterion = (i: number, text: string) =>
    setCriteria((cs) => cs.map((c, j) => (j === i ? { ...c, criterion: text } : c)))
  const setImportance = (i: number, imp: Importance) =>
    setCriteria((cs) => cs.map((c, j) => (j === i ? { ...c, importance: imp } : c)))
  const removeCriterion = (i: number) => setCriteria((cs) => cs.filter((_, j) => j !== i))
  const addCriterion = () =>
    setCriteria((cs) => [...cs, { criterion: '', importance: 'important' }])
  const confirm = () => {
    setStatus('confirmed')
    confirmCriteria(selected).catch(() => {
      /* sample mode / offline — UI already reflects confirmation */
    })
  }

  return (
    <div className="page">
      <PageBanner
        title="Job posts"
        subtitle={`${jobs.length} posts`}
        actions={<Button icon="plus">New job post</Button>}
      />
      <div className="jp-grid">
        <div className="jp-jobs">
          {jobs.map((j) => (
            <button
              key={j.jd_id}
              className={`jp-job ${j.jd_id === selected ? 'on' : ''}`}
              onClick={() => setSelected(j.jd_id)}
            >
              <div className="t">
                {j.title}
                <Badge variant={j.status === 'Active' ? 'strong' : 'neutral'}>{j.status ?? 'Draft'}</Badge>
              </div>
              <div className="m">
                <span><b>{j.applicants ?? 0}</b> applicants</span>
                {j.shortlisted != null ? <span><b>{j.shortlisted}</b> shortlisted</span> : <span>criteria pending</span>}
              </div>
            </button>
          ))}
        </div>

        <Card>
          <CardHeader>
            <SectionHeader title="Match criteria" subtitle={`${jobs.find((j) => j.jd_id === selected)?.title ?? ''} · generated by AI from the JD`} />
            <span className={`ce-status ${status}`} style={{ marginLeft: 'auto' }}>
              <Icon name={status === 'confirmed' ? 'check' : 'alert'} />
              {status === 'confirmed' ? 'Confirmed' : 'Draft — review to lock'}
            </span>
          </CardHeader>
          <CardBody>
            {criteria.map((c, i) => (
              <div className="crit-row" key={i}>
                <span className="grip"><Icon name="grip" /></span>
                <input
                  className="crit-input"
                  value={c.criterion}
                  placeholder="Describe the criterion…"
                  onChange={(e) => setCriterion(i, e.target.value)}
                  aria-label={`Criterion ${i + 1}`}
                />
                <select
                  className={`imp-select ${c.importance === 'must_have' ? 'must' : ''}`}
                  value={c.importance}
                  onChange={(e) => setImportance(i, e.target.value as Importance)}
                  aria-label={`Importance for criterion ${i + 1}`}
                >
                  {IMPORTANCE.map((o) => (
                    <option key={o.value} value={o.value}>
                      {o.label}
                    </option>
                  ))}
                </select>
                <button className="crit-rm" onClick={() => removeCriterion(i)} aria-label="Remove criterion">
                  <Icon name="x" />
                </button>
              </div>
            ))}
            <button className="crit-add" onClick={addCriterion}>
              <Icon name="plus" />Add criterion
            </button>
          </CardBody>
          <CardFooter>
            <Button icon="check" onClick={confirm} disabled={status === 'confirmed'}>
              {status === 'confirmed' ? 'Confirmed' : 'Confirm criteria'}
            </Button>
            <Button variant="ghost" onClick={() => setStatus('draft')}>Regenerate</Button>
            <span className="ce-note">Scoring locks to these weights once confirmed. Candidates aren't scored until then.</span>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}
